### ISSUE TITLE
System.FormatException: Input string was not in a correct format.

### ISSUE THREAD

**Issue by neron5** [abevol/KingdomMod#6]
[Message: Preloader] BepInEx 6.0.0-be.670 - KingdomTwoCrowns
[Message: Preloader] Built from commit 42a6727370c2b9356fc043ea601410540a8b4042
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 32-bit (x86)
[Info   :   BepInEx] Running under Unity 2019.4.13f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Message:InteropManager] Downloading unity base libraries
[Message:InteropManager] Extracting downloaded unity base libraries
[Message:InteropManager] Running Cpp2IL to generate dummy assemblies
[Info   :    Cpp2IL] [Library] Initializing Metadata...
[Info   :    Cpp2IL] [Library] Using actual IL2CPP Metadata version 24,3
[Info   :    Cpp2IL] [Library] Initialized Metadata in 388ms
[Info   :    Cpp2IL] [Library] Using binary type Portable Executable (from LibCpp2IL)
[Info   :    Cpp2IL] [Library] Searching Binary for Required Data...
[Info   :    Cpp2IL] [Library] Got Binary codereg: 0x119F92F0, metareg: 0x119F9A10 in 137ms.
[Info   :    Cpp2IL] [Library] Initializing Binary...
[Info   :    Cpp2IL] [Library] Initialized Binary in 160ms
[Info   :    Cpp2IL] [Library] Mapping Globals...
[Info   :    Cpp2IL] [Library] OK (30ms)
[Info   :    Cpp2IL] [Library] Mapping pointers to Il2CppMethodDefinitions...
[Info   :    Cpp2IL] [Library] Processed 95302 OK (41ms)
[Info   :    Cpp2IL] [Program] Creating application model...
[Info   :    Cpp2IL] [Program] Application model created in 1277,8828ms
[Info   :InteropManager] Cpp2IL finished in 00:00:06.9239716
[Info   :InteropManager] Generating interop assemblies
[Info   :Il2CppInteropGen] Reading assemblies...
[Info   :Il2CppInteropGen] Done in 00:00:00.0544462
[Info   :Il2CppInteropGen] Reading unity assemblies...
[Info   :Il2CppInteropGen] Done in 00:00:00.0120268
[Info   :Il2CppInteropGen] Creating rewrite assemblies...
[Info   :Il2CppInteropGen] Done in 00:00:00.0128372
[Info   :Il2CppInteropGen] Computing renames...
[Info   :Il2CppInteropGen] Done in 00:00:00.0792405
[Info   :Il2CppInteropGen] Creating typedefs...
[Info   :Il2CppInteropGen] Done in 00:00:00.0545131
[Info   :Il2CppInteropGen] Computing struct blittability...
[Info   :Il2CppInteropGen] Done in 00:00:00.0657601
[Info   :Il2CppInteropGen] Filling typedefs...
[Info   :Il2CppInteropGen] Done in 00:00:00.0430301
[Info   :Il2CppInteropGen] Filling generic constraints...
[Info   :Il2CppInteropGen] Done in 00:00:00.0059015
[Info   :Il2CppInteropGen] Creating members...
[Info   :Il2CppInteropGen] Done in 00:00:01.9052635
[Info   :Il2CppInteropGen] Scanning method cross-references...
[Info   :Il2CppInteropGen] Done in 00:00:00.0045759
[Info   :Il2CppInteropGen] Finalizing method declarations...
[Info   :Il2CppInteropGen] Done in 00:00:01.7402867
[Info   :Il2CppInteropGen] 0 total potentially dead methods
[Info   :Il2CppInteropGen] Filling method parameters...
[Info   :Il2CppInteropGen] Done in 00:00:00.4617456
[Info   :Il2CppInteropGen] Creating static constructors...
[Info   :Il2CppInteropGen] Done in 00:00:00.5104615
[Info   :Il2CppInteropGen] Creating value type fields...
[Info   :Il2CppInteropGen] Done in 00:00:00.0411249
[Info   :Il2CppInteropGen] Creating enums...
[Info   :Il2CppInteropGen] Done in 00:00:00.0600903
[Info   :Il2CppInteropGen] Creating IntPtr constructors...
[Info   :Il2CppInteropGen] Done in 00:00:00.1815057
[Info   :Il2CppInteropGen] Creating non-blittable struct constructors...
[Info   :Il2CppInteropGen] Done in 00:00:00.0071783
[Info   :Il2CppInteropGen] Creating generic method static constructors...
[Info   :Il2CppInteropGen] Done in 00:00:00.0551841
[Info   :Il2CppInteropGen] Creating field accessors...
[Info   :Il2CppInteropGen] Done in 00:00:01.0300155
[Info   :Il2CppInteropGen] Filling methods...
[Info   :Il2CppInteropGen] Done in 00:00:03.2431579
[Info   :Il2CppInteropGen] Generating implicit conversions...
[Info   :Il2CppInteropGen] Done in 00:00:00.0277315
[Info   :Il2CppInteropGen] Creating properties...
[Info   :Il2CppInteropGen] Done in 00:00:00.1142016
[Info   :Il2CppInteropGen] Unstripping types...
[Info   :Il2CppInteropGen] Done in 00:00:00.0411730
[Info   :Il2CppInteropGen] Unstripping fields...
[Info   :Il2CppInteropGen] Restored 563 fields
[Info   :Il2CppInteropGen] Failed to restore 3 fields
[Info   :Il2CppInteropGen] Done in 00:00:00.0123195
[Info   :Il2CppInteropGen] Unstripping methods...
[Info   :Il2CppInteropGen] Restored 14854 methods
[Info   :Il2CppInteropGen] Failed to restore 1056 methods
[Info   :Il2CppInteropGen] Done in 00:00:00.5521216
[Info   :Il2CppInteropGen] Unstripping method bodies...
[Info   :Il2CppInteropGen] IL unstrip statistics: 7117 successful, 2240 failed
[Info   :Il2CppInteropGen] Done in 00:00:00.5948730
[Info   :Il2CppInteropGen] Writing xref cache...
[Info   :Il2CppInteropGen] Done in 00:00:00.0217643
[Info   :Il2CppInteropGen] Writing assemblies...
[Info   :Il2CppInteropGen] Done in 00:00:01.0696086
[Info   :Il2CppInteropGen] Writing method pointer map...
[Info   :Il2CppInteropGen] Done in 00:00:00.0438428
[Info   :Il2CppInteropGen] Done!
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [KingdomMod.OverlayMap 2.2.0]
[Info   :KingdomMod.OverlayMap] Plugin KingdomMod.OverlayMap is loaded!
[Message:KingdomMod.OverlayMap] [130][ConfigBind] ConfigBind: KingdomMod.OverlayMap.cfg
[Message:KingdomMod.OverlayMap] [97][Initialize] Config prefab file: D:\Steamgames\steamapps\common\Kingdom Two Crowns\BepInEx\config\KingdomMod.OverlayMap.Style.cfg
[Message:KingdomMod.OverlayMap] [101][Initialize] Config prefab file do not exist: D:\Steamgames\steamapps\common\Kingdom Two Crowns\BepInEx\config\KingdomMod.OverlayMap.Style.cfg
[Message:KingdomMod.OverlayMap] [97][Initialize] Config prefab file: D:\Steamgames\steamapps\common\Kingdom Two Crowns\BepInEx\config\KingdomMod.OverlayMap.Language.en-US.cfg
[Message:KingdomMod.OverlayMap] [101][Initialize] Config prefab file do not exist: D:\Steamgames\steamapps\common\Kingdom Two Crowns\BepInEx\config\KingdomMod.OverlayMap.Language.en-US.cfg
[Message:KingdomMod.OverlayMap] [97][Initialize] Config prefab file: D:\Steamgames\steamapps\common\Kingdom Two Crowns\BepInEx\config\KingdomMod.OverlayMap.Language.zh-CN.cfg
[Message:KingdomMod.OverlayMap] [101][Initialize] Config prefab file do not exist: D:\Steamgames\steamapps\common\Kingdom Two Crowns\BepInEx\config\KingdomMod.OverlayMap.Language.zh-CN.cfg
[Message:KingdomMod.OverlayMap] [141][ConfigBind] ConfigFilePath: D:\Steamgames\steamapps\common\Kingdom Two Crowns\BepInEx\config\KingdomMod.OverlayMap.cfg
[Message:KingdomMod.OverlayMap] [142][ConfigBind] Language: system
[Message:KingdomMod.OverlayMap] [143][ConfigBind] StyleFile: KingdomMod.OverlayMap.Style.cfg
[Message:KingdomMod.OverlayMap] [145][ConfigBind] Loaded config: KingdomMod.OverlayMap.cfg
[Message:KingdomMod.OverlayMap] [176][OnLanguageChanged] OnLanguageChanged: system
[Message:KingdomMod.OverlayMap] [184][OnLanguageChanged] Language file: D:\Steamgames\steamapps\common\Kingdom Two Crowns\BepInEx\config\KingdomMod.OverlayMap.Language.ru-RU.cfg
[Warning:KingdomMod.OverlayMap] Language file do not exist: D:\Steamgames\steamapps\common\Kingdom Two Crowns\BepInEx\config\KingdomMod.OverlayMap.Language.ru-RU.cfg
[Warning:KingdomMod.OverlayMap] Language file do not exist: D:\Steamgames\steamapps\common\Kingdom Two Crowns\BepInEx\config\KingdomMod.OverlayMap.Language.ru-RU.cfg
[Warning:KingdomMod.OverlayMap] Try to use the default english language file: D:\Steamgames\steamapps\common\Kingdom Two Crowns\BepInEx\config\KingdomMod.OverlayMap.Language.en-US.cfg
[Message:KingdomMod.OverlayMap] [221][OnLanguageChanged] Try to bind Language file: KingdomMod.OverlayMap.Language.en-US.cfg
[Message:KingdomMod.OverlayMap] [345][ConfigBind] ConfigBind: KingdomMod.OverlayMap.Language.en-US.cfg
[Message:KingdomMod.OverlayMap] [433][ConfigBind] Loaded config: KingdomMod.OverlayMap.Language.en-US.cfg
[Message:KingdomMod.OverlayMap] [227][OnStyleFileChanged] OnStyleFileChanged: KingdomMod.OverlayMap.Style.cfg
[Message:KingdomMod.OverlayMap] [231][OnStyleFileChanged] Style file: D:\Steamgames\steamapps\common\Kingdom Two Crowns\BepInEx\config\KingdomMod.OverlayMap.Style.cfg
[Message:KingdomMod.OverlayMap] [251][OnStyleFileChanged] Try to bind style file: KingdomMod.OverlayMap.Style.cfg
[Message:KingdomMod.OverlayMap] [526][ConfigBind] ConfigBind: KingdomMod.OverlayMap.Style.cfg
[Message:KingdomMod.OverlayMap] [668][ConfigBind] Loaded config: KingdomMod.OverlayMap.Style.cfg
[Warning:Il2CppInterop] Method System.Collections.Generic.List`1[T] GetPayablesOfType[T]() on type KingdomMod.OverlayMap has unsupported return type System.Collections.Generic.List`1[T]
[Info   :Il2CppInterop] Registered mono type KingdomMod.OverlayMap in il2cpp domain
[Info   :   BepInEx] Loading [KingdomMod.StaminaBar 2.2.0]
[Info   :KingdomMod.StaminaBar] Plugin KingdomMod.StaminaBar is loaded!
[Info   :Il2CppInterop] Registered mono type KingdomMod.StaminaBar in il2cpp domain
[Message:   BepInEx] Chainloader startup complete
[Message:KingdomMod.OverlayMap] OverlayMap Start.
[Message:KingdomMod.StaminaBar] StaminaBar Start.
[Message:KingdomMod.OverlayMap] OnGameStart.
[Message:KingdomMod.OverlayMap] OnGameStart: _archiveFilename island-v35-c0-l4, Campaign 0, CurrentLand 4, currentChallenge 0
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Single.Parse(String s)
   at KingdomMod.OverlayMap.Config.ConfigEntryWrapper`1.StrToColor(String str) in D:\workspace\games\KingdomTwoCrowns\KingdomMapMod\OverlayMap\OverlayMap.Config.cs:line 55
   at KingdomMod.OverlayMap.Config.ConfigEntryWrapper`1.op_Implicit(ConfigEntryWrapper`1 d) in D:\workspace\games\KingdomTwoCrowns\KingdomMapMod\OverlayMap\OverlayMap.Config.cs:line 36
   at KingdomMod.OverlayMap.UpdateMinimapMarkList() in D:\workspace\games\KingdomTwoCrowns\KingdomMapMod\OverlayMap\OverlayMap.cs:line 369
   at KingdomMod.OverlayMap.Update() in D:\workspace\games\KingdomTwoCrowns\KingdomMapMod\OverlayMap\OverlayMap.cs:line 145
   at Trampoline_VoidThisKingdomMod.OverlayMapUpdate(IntPtr , Il2CppMethodInfo* )
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Single.Parse(String s)
   at KingdomMod.OverlayMap.Config.ConfigEntryWrapper`1.StrToColor(String str) in D:\workspace\games\KingdomTwoCrowns\KingdomMapMod\OverlayMap\OverlayMap.Config.cs:line 55
   at KingdomMod.OverlayMap.Config.ConfigEntryWrapper`1.op_Implicit(ConfigEntryWrapper`1 d) in D:\workspace\games\KingdomTwoCrowns\KingdomMapMod\OverlayMap\OverlayMap.Config.cs:line 36
   at KingdomMod.OverlayMap.UpdateMinimapMarkList() in D:\workspace\games\KingdomTwoCrowns\KingdomMapMod\OverlayMap\OverlayMap.cs:line 369
   at KingdomMod.OverlayMap.Update() in D:\workspace\games\KingdomTwoCrowns\KingdomMapMod\OverlayMap\OverlayMap.cs:line 145
   at Trampoline_VoidThisKingdomMod.OverlayMapUpdate(IntPtr , Il2CppMethodInfo* )
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Single.Parse(String s)
   at KingdomMod.OverlayMap.Config.ConfigEntryWrapper`1.StrToColor(String str) in D:\workspace\games\KingdomTwoCrowns\KingdomMapMod\OverlayMap\OverlayMap.Config.cs:line 55
   at KingdomMod.OverlayMap.Config.ConfigEntryWrapper`1.op_Implicit(ConfigEntryWrapper`1 d) in D:\workspace\games\KingdomTwoCrowns\KingdomMapMod\OverlayMap\OverlayMap.Config.cs:line 36
   at KingdomMod.OverlayMap.UpdateMinimapMarkList() in D:\workspace\games\KingdomTwoCrowns\KingdomMapMod\OverlayMap\OverlayMap.cs:line 369
   at KingdomMod.OverlayMap.Update() in D:\workspace\games\KingdomTwoCrowns\KingdomMapMod\OverlayMap\OverlayMap.cs:line 145
   at Trampoline_VoidThisKingdomMod.OverlayMapUpdate(IntPtr , Il2CppMethodInfo* )
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Single.Parse(String s)
   at KingdomMod.OverlayMap.Config.ConfigEntryWrapper`1.StrToColor(String str) in D:\workspace\games\KingdomTwoCrowns\KingdomMapMod\OverlayMap\OverlayMap.Config.cs:line 55
   at KingdomMod.OverlayMap.Config.ConfigEntryWrapper`1.op_Implicit(ConfigEntryWrapper`1 d) in D:\workspace\games\KingdomTwoCrowns\KingdomMapMod\OverlayMap\OverlayMap.Config.cs:line 36
   at KingdomMod.OverlayMap.UpdateMinimapMarkList() in D:\workspace\games\KingdomTwoCrowns\KingdomMapMod\OverlayMap\OverlayMap.cs:line 369
   at KingdomMod.OverlayMap.Update() in D:\workspace\games\KingdomTwoCrowns\KingdomMapMod\OverlayMap\OverlayMap.cs:line 145
   at Trampoline_VoidThisKingdomMod.OverlayMapUpdate(IntPtr , Il2CppMethodInfo* )
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Single.Parse(String s)
   at KingdomMod.OverlayMap.Config.ConfigEntryWrapper`1.StrToColor(String str) in D:\workspace\games\KingdomTwoCrowns\KingdomMapMod\OverlayMap\OverlayMap.Config.cs:line 55
   at KingdomMod.OverlayMap.Config.ConfigEntryWrapper`1.op_Implicit(ConfigEntryWrapper`1 d) in D:\workspace\games\KingdomTwoCrowns\KingdomMapMod\OverlayMap\OverlayMap.Config.cs:line 36
   at KingdomMod.OverlayMap.UpdateMinimapMarkList() in D:\workspace\games\KingdomTwoCrowns\KingdomMapMod\OverlayMap\OverlayMap.cs:line 369
   at KingdomMod.OverlayMap.Update() in D:\workspace\games\KingdomTwoCrowns\KingdomMapMod\OverlayMap\OverlayMap.cs:line 145
   at Trampoline_VoidThisKingdomMod.OverlayMapUpdate(IntPtr , Il2CppMethodInfo* )

**Comment by abevol** [comment]
看起来是你改动了`KingdomMod.OverlayMap.Style.cfg`配置文件里的[Portal].Color的配置，并将其设置成了一个不正确的值。
Unity.Color以RGB的比例来表示颜色值，也就是 R/255,G/255,B/255,A/255。
比如红色，如果您设置成了 Color=FF0000FF，或者 Color=FF,00,00,FF，这将不被接受。
正确的格式是，Color=1,0,0,1
另外，我更新了版本2.2.1，该版本将会打印出错的颜色配置选项信息，并将出错的颜色设置为白色，模组将继续正常工作。

It seems that you changed the configuration of [Portal].Color in the `KingdomMod.OverlayMap.Style.cfg` configuration file and set it to an incorrect value.
Unity.Color represents color values in RGB percentage, that is, R/255, G/255, B/255, A/255.
For example, the red color, if you set Color=FF0000FF, or Color=FF,00,00,FF, this will not be accepted.
The correct format is, Color=1,0,0,1
In addition, I updated version 2.2.1, which will print the wrong color configuration information and set the wrong color to white, and the mod will continue to work normally.

**Comment by neron5** [comment]
a fresh installation on existing saves gives:
[Error  :KingdomMod.OverlayMap] [63][StrToColor] Parse Color failed: ConfigEntry: [WallFoundation].Color, ConfigValue: 0.5,0.5,0.5,1
Exception: System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Single.Parse(String s)
   at KingdomMod.OverlayMap.Config.ConfigEntryWrapper`1.StrToColor(ConfigEntry`1 entry) in D:\workspace\games\KingdomTwoCrowns\KingdomMapMod\OverlayMap\OverlayMap.Config.cs:line 58
[Error  :KingdomMod.OverlayMap] [63][StrToColor] Parse Color failed: ConfigEntry: [River].Color, ConfigValue: 0.46,0.84,0.92,1
Exception: System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Single.Parse(String s)
   at KingdomMod.OverlayMap.Config.ConfigEntryWrapper`1.StrToColor(ConfigEntry`1 entry) in D:\workspace\games\KingdomTwoCrowns\KingdomMapMod\OverlayMap\OverlayMap.Config.cs:line 58

**Comment by abevol** [comment]
确定是float字符串解析的BUG，没有考虑到区域文化差异。
该问题已在[2.2.3](https://github.com/abevol/KingdomMod/releases/tag/2.2.3)版本中修复。
请使用该版本进行测试，如果没有问题请关闭该issue。

It is definitely a bug in float string parsing, which does not take into account regional cultural differences.
This issue has been fixed in version [2.2.3](https://github.com/abevol/KingdomMod/releases/tag/2.2.3).
Please use this version for testing. If there are no problems, please close this issue.

**Comment by neron5** [comment]
Thank you, everything is fine, you are breathtaking :smiley:
